import { Sidebar } from './components/sidebar.js';
import { Search } from './components/search.js';
import { Dashboard } from './components/dashboard.js';
import { Chat } from './components/chat.js';

class App {
    static init() {
        console.log("Initializing Nebulus Gantry (ES6)...");

        // 1. Sidebar
        let sidebarContainer = document.getElementById('nebulus-sidebar');
        if (!sidebarContainer) {
            sidebarContainer = document.createElement('div');
            sidebarContainer.id = 'nebulus-sidebar';
            document.body.prepend(sidebarContainer);
        }
        const sidebar = new Sidebar('nebulus-sidebar');

        // 2. Search
        const search = new Search('search-modal-global-container');

        // 3. Dashboard
        const dashboard = new Dashboard('nebulus-dashboard-container'); // Handles its own creation if id not found

        // 4. Chat
        const chat = new Chat(document.body); // Global listener approach

        // Expose for debugging & legacy interop
        window.NebulusApp = { sidebar, search, dashboard, chat };

        // Expose legacy-compatible global for Search/History clicks
        // Compatibility layer for HTML onclick attributes generated by some parts
        window.Nebulus = window.Nebulus || {};
        window.Nebulus.Chat = chat;
    }
}

// Auto-init when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', App.init);
} else {
    App.init();
}
