---
- name: Promote Nebulus Gantry Versions
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    project_root: "../../.."
    version_file: "{{ project_root }}/src/nebulus_gantry/version.py"
    config_file: "{{ project_root }}/.chainlit/config.toml"

  tasks:
    - name: Ensure version file exists
      ansible.builtin.stat:
        path: "{{ version_file }}"
      register: vfile

    - name: Fail if version file missing
      ansible.builtin.fail:
        msg: "Version file not found at {{ version_file }}"
      when: not vfile.stat.exists

    # --- Extract Current Versions ---
    - name: Get current UI_CSS_VERSION
      ansible.builtin.shell: grep -oP 'UI_CSS_VERSION.*"\K\d+' "{{ version_file }}"
      register: current_css_ver
      changed_when: false

    - name: Get current UI_JS_VERSION
      ansible.builtin.shell: grep -oP 'UI_JS_VERSION.*"\K\d+' "{{ version_file }}"
      register: current_js_ver
      changed_when: false

    - name: Set new versions
      ansible.builtin.set_fact:
        new_css_ver: "{{ current_css_ver.stdout | int + 1 }}"
        new_js_ver: "{{ current_js_ver.stdout | int + 1 }}"

    - name: Display promotion plan
      ansible.builtin.debug:
        msg:
          - "Promoting CSS: {{ current_css_ver.stdout }} -> {{ new_css_ver }}"
          - "Promoting JS:  {{ current_js_ver.stdout }} -> {{ new_js_ver }}"

    # --- Update version.py ---
    - name: Update UI_CSS_VERSION in version.py
      ansible.builtin.replace:
        path: "{{ version_file }}"
        regexp: 'UI_CSS_VERSION\s*=\s*(.*?)else\s*"\d+"'
        replace: 'UI_CSS_VERSION = \1else "{{ new_css_ver }}"'
        mode: '0644'

    - name: Update UI_JS_VERSION in version.py
      ansible.builtin.replace:
        path: "{{ version_file }}"
        regexp: 'UI_JS_VERSION\s*=\s*(.*?)else\s*"\d+"'
        replace: 'UI_JS_VERSION = \1else "{{ new_js_ver }}"'
        mode: '0644'

    # --- Update config.toml ---
    - name: Update CSS version in config.toml
      ansible.builtin.lineinfile:
        path: "{{ config_file }}"
        regexp: '^custom_css\s*='
        line: 'custom_css = "/public/style.css?v={{ new_css_ver }}"'
        mode: '0644'

    - name: Update JS version in config.toml
      ansible.builtin.lineinfile:
        path: "{{ config_file }}"
        regexp: '^custom_js\s*='
        line: 'custom_js = "/public/script.js?v={{ new_js_ver }}"'
        mode: '0644'

    - name: Promotion Complete
      ansible.builtin.debug:
        msg: "Versions promoted successfully. Run 'bin/gantry rebuild' to apply."
